### PR TITLE
onClick on a card to a specific issue

### PR DESCRIPTION
**Pull request by ktan114**
https://github.com/dillionverma/github-issues-explorer/issues/1

### CODE REVIEW

**Comment by dillionverma** [comment]
Looks good, except the styling seems messed up now.

image


Maybe, add the onClick prop to the `<Card />` componenet since I have done styling for that component specifically

**Comment by ktan114** [comment]
Yeah I can fix that.

**Comment by ktan114** [comment]
Done! I was actually having some trouble figuring out why I couldn't call onClick on the Card component directly so I decided to just pass everything down as props.

**Comment by dillionverma** [comment]
Awesome, everything is working good now! I will merge it in. Thanks so much for your help!
😄 🎉

**Pull request merged**
