### PR TITLE
Trblackw master

### PR DESCRIPTION
**Pull request by dillionverma**
@trblackw 

PR Fix

To fix, I went to your branch, ran `git rebase master` and resolved conflicts. Then it created a PR

### CODE REVIEW

**Comment by trblackw** [comment]
Cool so we’re good then?

**Comment by dillionverma** [comment]
Working correctly for me. Thanks a lot for PR! @trblackw

**Comment by trblackw** [comment]
Yeah man!

**Comment by trblackw** [comment]
Btw I noticed some overflow of the tags on certain repos that have a lot of
them, I can look into that tomorrow sometime. Are you seeing the same issue?

**Comment by dillionverma** [comment]
Sure, give me an example and I can check it out @trblackw

**Comment by trblackw** [comment]
https://github.com/Ignitus/Ignitus-Client-Side-Development

**Comment by dillionverma** [comment]
I see, we can open a new issue for that too :)

**Pull request merged**
