### PR TITLE
Included Pull requests filter for issues

### PR DESCRIPTION
**Pull request by trblackw**
I added the li for pull requests and filtered out any issues that were PRs in your reducers!

### CODE REVIEW

**Comment by trblackw** [comment]
This is a pretty sweet project, man! I dig it.

**Comment by dillionverma** [comment]
Dam, I have to admit I love the addition of the label colors! Didn't even know that was possible.
image

StyledComponents is a great idea! 
I'm glad you love the mini project 😆

**Comment by trblackw** [comment]
I guess vs code auto updated a bunch of crap in your package-lock.json. My b

**Comment by trblackw** [comment]
You can just disable the eslint settings for that line via `eslint-disable-line`

**Comment by dillionverma** [comment]
I just saw the package-lock, dw about it. I think its normal for it to change a bit.

Also, I just merged in #30 because it was super clean implementation. However, I still want you to add in styled components for the labels!

**Pull request closed without merging**
